# must be unique in a given SonarQube instance
sonar.projectKey=desr-sires-pga_support_n1_listem3u_8d9d0b62-afe8-4645-bc3c-e29119ece483
sonar.qualitygate.wait=true
sonar.projectName=listem3u
sonar.projectVersion=@RELEASE_VERSION@
sonar.projectBaseDir=src
sonar.sources=listem3u.py
sonar.exclusions=build/**,docs/**,devtools/**,.gitignore,dist/**,rapports/**,tests/**
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
sonar.python.coverage.reportPaths=public/tox_cov_py312.xml
sonar.qualitygate.timeout=300
sonar.coverage.exclusions=**test**
sonar.python.version=3.12

