#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
""" Created on 25 mars 2023
	@author: Nicolas Bruschi
	
	Configuration file for the Sphinx documentation builder.
	This file only contains a selection of the most common options. For a full
	list see the documentation:
	https://www.sphinx-doc.org/en/master/usage/configuration.html
	pip install sphinx-multiversion gitpython --user
	
	[Autres refs] :
	https://blog.stephane-robert.info/post/sphinx-documentation-multi-version/
	https://github.com/maltfield/rtd-github-pages
	
"""
# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

import os
import sys
#from git import Repo

PLATEFORMENAME = "gitlab"
# get environment variables
env_platefome_name = os.getenv("PLATEFORMENAME")

# set device name
if env_platefome_name is not None:
 PLATEFORMENAME = env_platefome_name.lower()

sys.path.insert(0, os.path.abspath('../src/'))


# -- Project information -----------------------------------------------------
# pylint: disable=invalid-name
project = 'listem3u'
# pylint: disable=invalid-name,redefined-builtin
copyright = '2023, Nicolas Bruschi 😀'
# pylint: disable=invalid-name
author = 'Nicolas Bruschi'

# The full version, including alpha/beta/rc tags
release = '@RELEASE_VERSION@'

today_fmt = '%Y %b %d à %H:%M'
LISTEM3U_DOC = 'listem3u Documentation'
# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [  'sphinx_rtd_theme', 'sphinx.ext.autodoc',\
								'sphinx.ext.autosummary', 'sphinx.ext.viewcode',\
								'sphinx.ext.githubpages', 'sphinx.ext.graphviz',\
								'sphinx_multiversion', 'sphinx.ext.autodoc',\
								'sphinx.ext.intersphinx',
]



# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = f'index_{PLATEFORMENAME}'
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'fr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', '.venv', 'envdev']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_logo = 'listem3u.png'
html_favicon = 'listem3u.ico'
html_last_updated_fmt = '%d %b %Y à %H:%M'

numfig = True

autosummary_generate = True
# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'listem3u'


# -- Options for LaTeX output ------------------------------------------------

# -- Options for manual page output ------------------------------------------
