[tox]
requires =
	tox>=4
env_list = lint, type, 3.1{0,1,2}
tox_root = ./

skipsdist = True

[testenv]
description = run unit tests
deps =
    pytest
    pytest-cov
commands =
    pytest --cov=src tests/
