[tox]
requires =
	tox>=4
env_list = clean, lint, type, py3{10,11,12}
tox_root = ./

skipsdist = True

[gh-actions]
# See https://pypi.org/project/tox-gh-actions/
python =
    3.10: py310
    3.11: py311
    3.12: py312

[testenv]
description = run unit tests
deps =
    pytest
    pytest-cov
depends =
    {py310,py311,py312}: clean
    report: py310,py311,py312
commands =
    pytest  --cov=src \
            --cov-append \ 
            --cov-report html:rapports/tox_cov_html_{env_name} \
            --cov-report xml:rapports/tox_cov_{env_name}.xml \
            tests/

[testenv:report]
deps = coverage
skip_install = true
commands =
    coverage report
    coverage html

[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase