run-name: ${{ github.actor }} is learning GitHub Actions ${{ GITHUB_SHA }}
on: [push]
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
        id: foo
        with:
          projectBaseDir: src
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
