run-name: GA ${{ github.event.head_commit.message }} ${{ github.sha }}
on: [push]
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: actions/listem3u@ad6eaef5aa70de59b29b50985b5ec8b4f05b9018
        with:
          #['repository', 'ref', 'token', 'ssh-key', 'ssh-known-hosts', \
          # 'ssh-strict', 'persist-credentials', 'path', 'clean', \
          # 'fetch-depth', 'lfs', 'submodules', 'set-safe-directory', \
          # 'github-server-url']
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
