name: Doc_Quality_Gate_Steps_File
# Workflow en plusieurs séquences pour déployer du contenu dynamique
# vers GitHub Pages et résultats pour sonar

#Documentations et refs:
#https://docs.github.com/en/actions/using-workflows/reusing-workflows

run-name: GA File ${{ github.event.head_commit.message }} ${{ github.sha }}

on:
  issues:
    types:
      - created
      - opened
  label:
    types:
      - created
  push:
    branches:
      - 19-plusieurs_yaml
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - releases

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  actions: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production
# deployments to complete.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-build:
    uses: bruschin/listem3u/.github/workflows/listem3u_file_build.yml@19-plusieurs_yaml
  call-github_pages:
    needs: call-build
    uses: bruschin/listem3u/.github/workflows/listem3u_file_github_pages.yml@19-plusieurs_yaml
  call-sonarqube:
    needs: call-build
    uses: bruschin/listem3u/.github/workflows/listem3u_file_sonarqube.yml@19-plusieurs_yaml
    secrets: inherit # pass all secrets
  call-clear_cache:
    needs: [ 'call-build', 'call-github_pages', 'call-sonarqube' ]
    uses: bruschin/listem3u/.github/workflows/listem3u_file_clear_cache.yml@19-plusieurs_yaml
