name: Sonarqube

on: ["workflow_call"]

defaults:
  run:
    shell: bash
  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  actions: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production
# deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  sonarqube:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      # restauration cache
      - uses: actions/cache@v3
        id: cache2
        with:
          path: |
            .git
            rapports
            docs/_build/html
            src
          key: rap-libellule-${{ github.sha }}
      - name: Pre sonar
        run: |
          sed -i -e "s/@SONAR_VERSION@/1.8/g" ./src/sonar-project.properties
          cp rapports/coverage*.xml src/
          cp rapports/shellcheck-rapport.json src/
          cat src/sonar-project.properties
      - name: SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: src
        env:
          name: github-pages
          # sonarcloud.io
          SONAR_HOST_URL: ${{ secrets.SONAR_IO_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_IO_TOKEN_CI }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # sonar.cloudmf.dev
          #SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          #SONAR_TOKEN: ${{ secrets.SONAR_REPAIRE_TOKEN }}
